# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ChiPy Algorithms SIG
email: chicago-sig-organizers@python.org
description: >- # this means to ignore newlines until "baseurl:"
  Algo SIG is ChiPy's special interest group where we discuss and practice all things algorithms.
baseurl: "/algosig" # the subpath of your site, e.g. /blog
url: "http://chicagopython.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ChicagoPython
github_username:  chicagopython

# Build settings
plugins:
  - jekyll-feed

theme: minima

header_pages:
  - name: About
    path: about.md
    icon: fa fa-book
  - name: Contribute
    path: contribute.md
    icon:
  - name: Connect
    icon: fa fa-users
    dropdown:
      - name: GitHub
        link: https://github.com/chicagopython
        icon: fa fa-github
      - name: Twitter
        link: https://twitter.com/ChicagoPython
        icon: fa fa-twitter
      - name: Email
        link: mailto:chicago-sig-organizers@python.org
        icon: fa fa-envelope

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
